### PR TITLE
upgrade CKEditor from v4.5.9 to v4.5.11

### PR DESCRIPTION
**Pull request by jxmai**
I also included all skins back to the new version since the original ckeditor package has moono only.

Sample test run:

image

```xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
     xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:p="http://primefaces.org/ui"
    xmlns:pe="http://primefaces.org/ui/extensions"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    >

    <h:head>
    </h:head>

    <h:body>
        <h:form>
            <pe:ckEditor id="editor"  
                        skin="office2013"
            >
            </pe:ckEditor>

        </h:form>
    </h:body>

 </ui:composition>
```

### CODE REVIEW

**Comment by jxmai** [comment]
The default theme is losing all icons for some reason.

**Comment by tandraschko** [comment]
Did you use the ResourceModifier class?

**Comment by jxmai** [comment]
I did. I guess I need to modify the ResourceModifier a little bit since the png ```t=????``` is difference. It used to be 35abfe but now is 3876e73.

snapshot2

As a result, the ResourceModifier failed to modify those resources.

**Comment by jxmai** [comment]
Worked. I will reopen it shortly.

snapshot2

**Pull request merged**
