### PR TITLE
update ckeditor to 4.5.9

### PR DESCRIPTION
**Pull request by nchaoufe**
I tried to update the ckeditor to 4.5.9 due to a need of my project. I also added some new themes.

### CODE REVIEW

**Comment by tandraschko** [comment]
Thanks for your PR but your PR broke the interfaceColor example in the showcase. Please fix it, otherwise i need to revert your PR.

**Comment by tandraschko** [comment]
Your ResourceModifier doesn't work correctly, too. On my console i get following:

\(icons.png\?t=a35abfe ###### with : ("#{resource['primefaces-extensions:/home/tandraschko/NetBeansProjects/primefaces-extensions/resources-ckeditor/src/main/resources/META-INF/resources/primefaces-extensions/ckeditor/skins/icy_orange/icons.png']}&t=a35abfe"

doesn't look right ;)

**Comment by tandraschko** [comment]
fixed the ResourceModifier but the interfaceColor is up to you.

**Comment by nchaoufe** [comment]
Ok thanks for your feedback, I'll try to fix the interfaceColor issue.

**Pull request merged**
