### PR TITLE
Fixed #418 - Office 2013 Skin Firefox compatibility

### PR DESCRIPTION
**Pull request by jxmai**
For https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/418

Fixed the firefox compatibility issue with office 2013 skin

snapshot2

I also did a test run on the showcase. No regression

snapshot2

### CODE REVIEW

**Comment by tandraschko** [comment]
Sorry but only +0 from my side
every update will overwrite your changes, therefore you need to fix it in CKEditor. I already pushed some fixes to CKEditor in the past.

**Comment by jxmai** [comment]
Here is what I have thought and done so far:

Part 1. Since the theme works with Firefox in plain html but not JSF/PFE, I tried to compare their differences.

Part 2. I downloaded the skin and I started to compare the existing editor.css. On the left is the editor.css after ResourceModifier, on the right is the original css. Unlike moono theme, the ```t=???``` never exist in the original file but it exists in the ResourceModified file. 

snapshot2

Part 3. I removed the ```t=???``` in the ResourceModifier since it did not exist in office2013 and ran ResourceModifer again for this skin only. (I did not push this part)

```java

                // icons.png
                fileContent = fileContent.replaceAll("url\\(icons.png\\",
                        "url\\(\"#{resource['primefaces-extensions:" + relativeSkinPath + "/icons.png']}\"");
                
				FileUtils.writeStringToFile(resourceToModify, fileContent);
			}
```

Part 4. I replaced all the files inside office2013 by the newly generated files.

---

**Comment by tandraschko** [comment]
So please enhance the resource modifier, otherwise your changes will be
overwritten next time

Am Freitag, 28. Oktober 2016 schrieb jxmai :

**Comment by jxmai** [comment]
@tandraschko One thing I noticed is that if I made the skin.js (in office2013 for example) to empty, Chrome still work fine but Firefox will fail to render the editor (An error will be generated from console). **This is the key as far as I can see.** Any inside logic about the empty js?

I think we need to use the default skin.js instead of an empty js in this case. This issue seems to be not about the resourceModifier.

```
WARNING: JSF1064: Unable to find or serve resource, ckeditor/skins/office2013/editor_gecko.css, from library, primefaces-extensions.

```

**Comment by tandraschko** [comment]
I think we should only add a empty skin.js if NO skin.js is available in the directory. Otherwise we should leave the original.

**Comment by jxmai** [comment]
Make sense. The fix was OK then. (the update guide might need to improve a bit)

**Pull request merged**
