### PR TITLE
CKEditor V 4.9.1 upgrade

### PR DESCRIPTION
**Pull request by jxmai**
Please review and give it a try. Some test run screenshots below

---

http://localhost:8080/primeext-showcase/sections/ckEditor/basicUsage.jsf

image

http://localhost:8080/primeext-showcase/sections/ckEditor/multipleEditors.jsf

image

http://localhost:8080/primeext-showcase/sections/ckEditor/customToolbar.jsf

image

### CODE REVIEW

**Comment by melloware** [comment]
This is fantastic work.  And you are right I didn't realize how much you had to modify to make this work!

**Comment by jxmai** [comment]
No problem! The key is to modify the resources and the existing ResourceModifier can handle most of the work already. The difficult part is that each upgrade there are some changes such as new plugins, line breaks etc so that we need to check the log and see if anything left.

The next step is to beautify the  ckeditor.js and check the minified source in order to add new rules inside  ResourceModifier, re-run again and check again until the modifer does the job correctly. 

The reason I broke down the commits is that I can check  `git diff` to make sure everything works as desired.

**Comment by jxmai** [comment]
@melloware I think we can merge it for now. To fix any further issue when it shows up.

**Comment by melloware** [comment]
Confirmed and merged!

**Pull request merged**
